---
# Ansible Task
# date: '20/02/17'

# Certificates Tasks
# copy backup certificates on both node (if more than one)
# copy common certificate on the secondary node

- include_vars: vars/certs_var.yml

- block:
  - name: Upload Certificate to {{inventory_hostname}}
    copy:
     src: '{{ssl_local_store}}/private/{{inventory_hostname}}/letsencrypt.tar.gz'
     dest: $HOME
  - name: Upload Certificate for MX on other node
    copy:
      src: '{{ssl_local_store}}/private/mxgw.tar'
      dest: $HOME
    when: "'{{ssl_master}}' not in inventory_hostname"
  - name: Extract certs
    command: tar zxf $HOME/letsencrypt.tar.gz -C '{{local_dir}}'
  - name: Extract MX cert
    command: tar xf $HOME/mxgw.tar -C '{{local_dir}}'
    when: "'{{ssl_master}}' not in inventory_hostname"
  - name: Fixing Files Permissions
    command: find "{{le_dir}}" -type f -exec chmod 640 {} \;
  - name: Fixing Directory Permissions
    command: find "{{le_dir}}" -type d -exec chmod 750 {} \;
  - name: Chowning
    command: chown -R root:wheel "{{le_dir}}"

  when: (enable_le == true)

