---
# Ansible Task
# date: '19/02/17'

# Configure Custom Poudriere Repository
# default is to use FreeBSD repo for standard pkgs

- name: Install certificates
  command: pkg install -y ca_root_nss

- name: Create Repo dir
  file:
    path: /usr/local/etc/pkg/repos
    state: directory
    mode: 0750

- name: Copy Cert Files
  copy:
    src: files/certificates/ssl/certs/{{default_repo_key}}
    dest: /usr/local/etc/ssl/certs/
    owner: root
    group: wheel
    mode: 0600

- name: Copy Repo Files Poudriere
  template:
    src: templates/pkg/poudriere.conf.j2
    dest: /usr/local/etc/pkg/repos/poudriere.conf
    owner: root
    group: wheel
    mode: 0600
    backup: true

- name: Copy Repo Files FreeBSD
  template:
    src: templates/pkg/FreeBSD.conf.j2
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: 0600
    backup: true

- name: Update PKGs
  command: pkg update

- name: Audit PKGs
  command: pkg audit -F