---
# tasks file for mail_gw

- block:
  - name: Check ENV VARS before starting up
    include: test_vars.yml
    when: (debug_vars == true)

- block:
  - name: System Basic Configuration
    include: system_basic.yml
    when: (system_configured == false)

- block:
  - name: Create Repositories
    include: create_repo.yml
    when: (repo_configured == false)

- block:
  - name: System Update
    include: system_update.yml
    when: (check_system_update == true)

- block:
  - name: Install System Software
    include: system_sw_base.yml
    when: (sw_base == true)

- block:
  - name: Certificates
    include: certs.yml
