---
# tasks file for mail_gw

- name: Debug Mode
  command: echo ""
  tags: test

- debug:
    msg: Entering in Test Mode

- debug:
    msg: "default group is: '{{ default_group }}'"

- debug:
    msg: "REPO enabled? '{{ default_repo_enabled }}'"
